id: I66D9445D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T06:30:40+00:00'
last_modified: '2022-06-07T20:37:43.703803+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6347
  title: བོད་ཡུལ་གྱི་གེ་སར་རྒྱལ་པོའི་ཤུལ་རྟེན་གྱི་རྣམ་བཤད་རབ་གསལ་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    875E:
      image_group_id: I1KG8295
      title: ''
      total_pages: 478
      order: 1
      base_file: 875E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
