id: P004151
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6347
  title: བོད་ཡུལ་གྱི་གེ་སར་རྒྱལ་པོའི་ཤུལ་རྟེན་གྱི་རྣམ་བཤད་རབ་གསལ་མེ་ལོང་།
  author: ''
  volumes:
    de372434eb244d75bd7464ceecaf162b:
      image_group_id: I1KG8295
      title: ''
      volume_number: 1
      total_pages: 478
